<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>MonoMelon;Il2CppMelon</Configurations>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'MonoMelon'">
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Il2CppMelon'">
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../S1API/S1API.csproj" />
  </ItemGroup>
</Project>
